//https://nookipedia.com/w/index.php?title=Special%3ACargoQuery&tables=nh_bug%2C+&fields=+nh_bug.index%2C+nh_bug.name%2C+nh_bug.render_url+%3D+picture%2C+nh_bug.image_url+%3D+icon%2C+nh_bug.sell_nook%2C+nh_bug.location%2C+nh_bug.weather%2C+nh_bug.n_m1%2C+nh_bug.n_m2%2C+nh_bug.n_m3%2C+nh_bug.n_m4%2C+nh_bug.n_m5%2C+nh_bug.n_m6%2C+nh_bug.n_m7%2C+nh_bug.n_m8%2C+nh_bug.n_m9%2C+nh_bug.n_m10%2C+nh_bug.n_m11%2C+nh_bug.n_m12%2C+nh_bug.s_m1%2C+nh_bug.s_m2%2C+nh_bug.s_m3%2C+nh_bug.s_m4%2C+nh_bug.s_m5%2C+nh_bug.s_m6%2C+nh_bug.s_m7%2C+nh_bug.s_m8%2C+nh_bug.s_m9%2C+nh_bug.s_m10%2C+nh_bug.s_m11%2C+nh_bug.s_m12%2C+nh_bug.time%2C&where=&join_on=&group_by=&having=&order_by%5B0%5D=&order_by_options%5B0%5D=ASC&limit=1000&offset=0&format=
const bugArr = 
[
    {
        "index": 1,
        "name": "Common Butterfly",
        "picture": "https://dodo.ac/np/images/9/9f/Common_Butterfly_NH.png",
        "icon": "https://dodo.ac/np/images/f/f8/Common_Butterfly_NH_Icon.png",
        "sell_nook": 160,
        "location": "Flying",
        "weather": "Any except rain",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM \u2013 7 PM"
    },
    {
        "index": 2,
        "name": "Yellow Butterfly",
        "picture": "https://dodo.ac/np/images/7/74/Yellow_Butterfly_NH.png",
        "icon": "https://dodo.ac/np/images/4/43/Yellow_Butterfly_NH_Icon.png",
        "sell_nook": 160,
        "location": "Flying",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM \u2013\u00a07 PM"
    },
    {
        "index": 3,
        "name": "Tiger Butterfly",
        "picture": "https://dodo.ac/np/images/e/e1/Tiger_Butterfly_NH.png",
        "icon": "https://dodo.ac/np/images/b/b6/Tiger_Butterfly_NH_Icon.png",
        "sell_nook": 240,
        "location": "Flying",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM \u2013 7 PM"
    },
    {
        "index": 4,
        "name": "Peacock Butterfly",
        "picture": "https://dodo.ac/np/images/8/8e/Peacock_Butterfly_NH.png",
        "icon": "https://dodo.ac/np/images/7/77/Peacock_Butterfly_NH_Icon.png",
        "sell_nook": 2500,
        "location": "Flying near blue, purple, and black flowers",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM \u2013 7 PM"
    },
    {
        "index": 5,
        "name": "Common Bluebottle",
        "picture": "https://dodo.ac/np/images/b/b3/Common_Bluebottle_NH.png",
        "icon": "https://dodo.ac/np/images/2/21/Common_Bluebottle_NH_Icon.png",
        "sell_nook": 300,
        "location": "Flying",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM \u2013 7 PM"
    },
    {
        "index": 6,
        "name": "Paper Kite Butterfly",
        "picture": "https://dodo.ac/np/images/c/c7/Paper_Kite_Butterfly_NH.png",
        "icon": "https://dodo.ac/np/images/9/9e/Paper_Kite_Butterfly_NH_Icon.png",
        "sell_nook": 1000,
        "location": "Flying near flowers",
        "weather": "Any except rain",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 7 PM"
    },
    {
        "index": 7,
        "name": "Great Purple Emperor",
        "picture": "https://dodo.ac/np/images/3/3f/Great_Purple_Emperor_NH.png",
        "icon": "https://dodo.ac/np/images/8/81/Great_Purple_Emperor_NH_Icon.png",
        "sell_nook": 3000,
        "location": "Flying near flowers",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM \u2013 7 PM"
    },
    {
        "index": 8,
        "name": "Monarch Butterfly",
        "picture": "https://dodo.ac/np/images/e/ec/Monarch_Butterfly_NH.png",
        "icon": "https://dodo.ac/np/images/3/38/Monarch_Butterfly_NH_Icon.png",
        "sell_nook": 140,
        "location": "Flying near flowers",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 AM \u2013 5 PM"
    },
    {
        "index": 9,
        "name": "Emperor Butterfly",
        "picture": "https://dodo.ac/np/images/f/f1/Emperor_Butterfly_NH.png",
        "icon": "https://dodo.ac/np/images/c/cf/Emperor_Butterfly_NH_Icon.png",
        "sell_nook": 4000,
        "location": "Flying near flowers",
        "weather": "Any except rain",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "5 PM \u2013 8 AM"
    },
    {
        "index": 10,
        "name": "Agrias Butterfly",
        "picture": "https://dodo.ac/np/images/d/db/Agrias_Butterfly_NH.png",
        "icon": "https://dodo.ac/np/images/6/60/Agrias_Butterfly_NH_Icon.png",
        "sell_nook": 3000,
        "location": "Flying near flowers",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 11,
        "name": "Rajah Brookes Birdwing",
        "picture": "https://dodo.ac/np/images/b/b7/Rajah_Brooke%27s_Birdwing_NH.png",
        "icon": "https://dodo.ac/np/images/8/81/Rajah_Brooke%27s_Birdwing_NH_Icon.png",
        "sell_nook": 2500,
        "location": "Flying near flowers",
        "weather": "Any except rain",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 12,
        "name": "Queen Alexandras Birdwing",
        "picture": "https://dodo.ac/np/images/8/8a/Queen_Alexandra%27s_Birdwing_NH.png",
        "icon": "https://dodo.ac/np/images/b/bb/Queen_Alexandra%27s_Birdwing_NH_Icon.png",
        "sell_nook": 4000,
        "location": "Flying near flowers",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 4 PM"
    },
    {
        "index": 13,
        "name": "Moth",
        "picture": "https://dodo.ac/np/images/a/ab/Moth_NH.png",
        "icon": "https://dodo.ac/np/images/a/a0/Moth_NH_Icon.png",
        "sell_nook": 130,
        "location": "Flying near light sources",
        "weather": "Any except rain",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM \u2013 4 AM"
    },
    {
        "index": 14,
        "name": "Atlas Moth",
        "picture": "https://dodo.ac/np/images/a/a4/Atlas_Moth_NH.png",
        "icon": "https://dodo.ac/np/images/7/7f/Atlas_Moth_NH_Icon.png",
        "sell_nook": 3000,
        "location": "On trees (any kind)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM \u2013 4 AM"
    },
    {
        "index": 15,
        "name": "Madagascan Sunset Moth",
        "picture": "https://dodo.ac/np/images/c/c8/Madagascan_Sunset_Moth_NH.png",
        "icon": "https://dodo.ac/np/images/6/69/Madagascan_Sunset_Moth_NH_Icon.png",
        "sell_nook": 2500,
        "location": "Flying near flowers",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 4 PM"
    },
    {
        "index": 16,
        "name": "Long Locust",
        "picture": "https://dodo.ac/np/images/8/8c/Long_Locust_NH.png",
        "icon": "https://dodo.ac/np/images/9/9d/Long_Locust_NH_Icon.png",
        "sell_nook": 200,
        "location": "On the ground",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 7 PM"
    },
    {
        "index": 17,
        "name": "Migratory Locust",
        "picture": "https://dodo.ac/np/images/8/8b/Migratory_Locust_NH.png",
        "icon": "https://dodo.ac/np/images/d/d0/Migratory_Locust_NH_Icon.png",
        "sell_nook": 600,
        "location": "On the ground",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM \u2013 7 PM"
    },
    {
        "index": 18,
        "name": "Rice Grasshopper",
        "picture": "https://dodo.ac/np/images/d/d4/Rice_Grasshopper_NH.png",
        "icon": "https://dodo.ac/np/images/7/78/Rice_Grasshopper_NH_Icon.png",
        "sell_nook": 400,
        "location": "On the ground",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM \u2013 7 PM"
    },
    {
        "index": 19,
        "name": "Grasshopper",
        "picture": "https://dodo.ac/np/images/1/1d/Grasshopper_NH.png",
        "icon": "https://dodo.ac/np/images/3/37/Grasshopper_NH_Icon.png",
        "sell_nook": 160,
        "location": "On the ground",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 20,
        "name": "Cricket",
        "picture": "https://dodo.ac/np/images/1/1c/Cricket_NH.png",
        "icon": "https://dodo.ac/np/images/8/8f/Cricket_NH_Icon.png",
        "sell_nook": 130,
        "location": "On the ground",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM \u2013 8 AM"
    },
    {
        "index": 21,
        "name": "Bell Cricket",
        "picture": "https://dodo.ac/np/images/d/d2/Bell_Cricket_NH.png",
        "icon": "https://dodo.ac/np/images/4/4a/Bell_Cricket_NH_Icon.png",
        "sell_nook": 430,
        "location": "On the ground",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM \u2013 8 AM"
    },
    {
        "index": 22,
        "name": "Mantis",
        "picture": "https://dodo.ac/np/images/d/da/Mantis_NH.png",
        "icon": "https://dodo.ac/np/images/4/4e/Mantis_NH_Icon.png",
        "sell_nook": 430,
        "location": "On flowers",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 23,
        "name": "Orchid Mantis",
        "picture": "https://dodo.ac/np/images/c/cd/Orchid_Mantis_NH.png",
        "icon": "https://dodo.ac/np/images/a/a7/Orchid_Mantis_NH_Icon.png",
        "sell_nook": 2400,
        "location": "On white flowers",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 24,
        "name": "Honeybee",
        "picture": "https://dodo.ac/np/images/8/8b/Honeybee_NH.png",
        "icon": "https://dodo.ac/np/images/5/51/Honeybee_NH_Icon.png",
        "sell_nook": 200,
        "location": "Flying near flowers",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 25,
        "name": "Wasp",
        "picture": "https://dodo.ac/np/images/b/bb/Wasp_NH.png",
        "icon": "https://dodo.ac/np/images/a/a5/Wasp_NH_Icon.png",
        "sell_nook": 2500,
        "location": "Shaking trees",
        "weather": "Any weather",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 26,
        "name": "Brown Cicada",
        "picture": "https://dodo.ac/np/images/2/2e/Brown_Cicada_NH.png",
        "icon": "https://dodo.ac/np/images/4/44/Brown_Cicada_NH_Icon.png",
        "sell_nook": 250,
        "location": "On trees (hardwood and cedar)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 27,
        "name": "Robust Cicada",
        "picture": "https://dodo.ac/np/images/8/8c/Robust_Cicada_NH.png",
        "icon": "https://dodo.ac/np/images/a/a2/Robust_Cicada_NH_Icon.png",
        "sell_nook": 300,
        "location": "On trees (hardwood and cedar)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 28,
        "name": "Giant Cicada",
        "picture": "https://dodo.ac/np/images/5/59/Giant_Cicada_NH.png",
        "icon": "https://dodo.ac/np/images/e/e3/Giant_Cicada_NH_Icon.png",
        "sell_nook": 500,
        "location": "On trees (hardwood and cedar)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 29,
        "name": "Walker Cicada",
        "picture": "https://dodo.ac/np/images/8/80/Walker_Cicada_NH.png",
        "icon": "https://dodo.ac/np/images/f/f8/Walker_Cicada_NH_Icon.png",
        "sell_nook": 400,
        "location": "On trees (hardwood and cedar)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 30,
        "name": "Evening Cicada",
        "picture": "https://dodo.ac/np/images/f/f6/Evening_Cicada_NH.png",
        "icon": "https://dodo.ac/np/images/b/ba/Evening_Cicada_NH_Icon.png",
        "sell_nook": 550,
        "location": "On trees (hardwood and cedar)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 AM \u2013 8 AM &amp; 4 PM \u2013 7 PM"
    },
    {
        "index": 31,
        "name": "Cicada Shell",
        "picture": "https://dodo.ac/np/images/7/77/Cicada_Shell_NH.png",
        "icon": "https://dodo.ac/np/images/d/d1/Cicada_Shell_NH_Icon.png",
        "sell_nook": 10,
        "location": "On trees (hardwood and cedar)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 32,
        "name": "Red Dragonfly",
        "picture": "https://dodo.ac/np/images/1/1d/Red_Dragonfly_NH.png",
        "icon": "https://dodo.ac/np/images/0/09/Red_Dragonfly_NH_Icon.png",
        "sell_nook": 180,
        "location": "Flying near water",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM \u2013 7 PM"
    },
    {
        "index": 33,
        "name": "Darner Dragonfly",
        "picture": "https://dodo.ac/np/images/5/57/Darner_Dragonfly_NH.png",
        "icon": "https://dodo.ac/np/images/5/5c/Darner_Dragonfly_NH_Icon.png",
        "sell_nook": 230,
        "location": "Flying near water",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 34,
        "name": "Banded Dragonfly",
        "picture": "https://dodo.ac/np/images/6/6e/Banded_Dragonfly_NH.png",
        "icon": "https://dodo.ac/np/images/3/35/Banded_Dragonfly_NH_Icon.png",
        "sell_nook": 4500,
        "location": "Flying near water",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 35,
        "name": "Damselfly",
        "picture": "https://dodo.ac/np/images/f/f6/Damselfly_NH.png",
        "icon": "https://dodo.ac/np/images/c/c8/Damselfly_NH_Icon.png",
        "sell_nook": 500,
        "location": "Flying near water",
        "weather": "Any except rain",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 36,
        "name": "Firefly",
        "picture": "https://dodo.ac/np/images/5/50/Firefly_NH.png",
        "icon": "https://dodo.ac/np/images/d/d6/Firefly_NH_Icon.png",
        "sell_nook": 300,
        "location": "Flying near water",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "7 PM \u2013 4 AM"
    },
    {
        "index": 37,
        "name": "Mole Cricket",
        "picture": "https://dodo.ac/np/images/8/89/Mole_Cricket_NH.png",
        "icon": "https://dodo.ac/np/images/4/4f/Mole_Cricket_NH_Icon.png",
        "sell_nook": 500,
        "location": "Underground",
        "weather": "Any weather",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 38,
        "name": "Pondskater",
        "picture": "https://dodo.ac/np/images/e/ea/Pondskater_NH.png",
        "icon": "https://dodo.ac/np/images/1/1f/Pondskater_NH_Icon.png",
        "sell_nook": 130,
        "location": "On rivers and ponds",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 7 PM"
    },
    {
        "index": 39,
        "name": "Diving Beetle",
        "picture": "https://dodo.ac/np/images/0/0e/Diving_Beetle_NH.png",
        "icon": "https://dodo.ac/np/images/7/78/Diving_Beetle_NH_Icon.png",
        "sell_nook": 800,
        "location": "On rivers and ponds",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 7 PM"
    },
    {
        "index": 40,
        "name": "Giant Water Bug",
        "picture": "https://dodo.ac/np/images/6/68/Giant_Water_Bug_NH.png",
        "icon": "https://dodo.ac/np/images/8/86/Giant_Water_Bug_NH_Icon.png",
        "sell_nook": 2000,
        "location": "On rivers and ponds",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM \u2013 8 AM"
    },
    {
        "index": 41,
        "name": "Stinkbug",
        "picture": "https://dodo.ac/np/images/5/5b/Stinkbug_NH.png",
        "icon": "https://dodo.ac/np/images/4/42/Stinkbug_NH_Icon.png",
        "sell_nook": 120,
        "location": "On flowers",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 42,
        "name": "Man-Faced Stink Bug",
        "picture": "https://dodo.ac/np/images/1/1e/Man-Faced_Stink_Bug_NH.png",
        "icon": "https://dodo.ac/np/images/a/ac/Man-Faced_Stink_Bug_NH_Icon.png",
        "sell_nook": 1000,
        "location": "On flowers",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM \u2013 8 AM"
    },
    {
        "index": 43,
        "name": "Ladybug",
        "picture": "https://dodo.ac/np/images/3/33/Ladybug_NH.png",
        "icon": "https://dodo.ac/np/images/0/08/Ladybug_NH_Icon.png",
        "sell_nook": 200,
        "location": "On flowers",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM \u2013 5 PM"
    },
    {
        "index": 44,
        "name": "Tiger Beetle",
        "picture": "https://dodo.ac/np/images/a/a0/Tiger_Beetle_NH.png",
        "icon": "https://dodo.ac/np/images/5/58/Tiger_Beetle_NH_Icon.png",
        "sell_nook": 1500,
        "location": "On the ground",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 45,
        "name": "Jewel Beetle",
        "picture": "https://dodo.ac/np/images/8/82/Jewel_Beetle_NH.png",
        "icon": "https://dodo.ac/np/images/4/43/Jewel_Beetle_NH_Icon.png",
        "sell_nook": 2400,
        "location": "On tree stumps",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 46,
        "name": "Violin Beetle",
        "picture": "https://dodo.ac/np/images/1/16/Violin_Beetle_NH.png",
        "icon": "https://dodo.ac/np/images/8/86/Violin_Beetle_NH_Icon.png",
        "sell_nook": 450,
        "location": "On tree stumps",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 47,
        "name": "Citrus Long-Horned Beetle",
        "picture": "https://dodo.ac/np/images/2/24/Citrus_Long-Horned_Beetle_NH.png",
        "icon": "https://dodo.ac/np/images/9/9a/Citrus_Long-Horned_Beetle_NH_Icon.png",
        "sell_nook": 350,
        "location": "On tree stumps",
        "weather": "Any except rain",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 48,
        "name": "Rosalia Batesi Beetle",
        "picture": "https://dodo.ac/np/images/4/44/Rosalia_Batesi_Beetle_NH.png",
        "icon": "https://dodo.ac/np/images/7/7c/Rosalia_Batesi_Beetle_NH_Icon.png",
        "sell_nook": 3000,
        "location": "On tree stumps",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 49,
        "name": "Blue Weevil Beetle",
        "picture": "https://dodo.ac/np/images/c/c3/Blue_Weevil_Beetle_NH.png",
        "icon": "https://dodo.ac/np/images/2/20/Blue_Weevil_Beetle_NH_Icon.png",
        "sell_nook": 800,
        "location": "On palm trees",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 50,
        "name": "Dung Beetle",
        "picture": "https://dodo.ac/np/images/f/f8/Dung_Beetle_NH.png",
        "icon": "https://dodo.ac/np/images/c/c4/Dung_Beetle_NH_Icon.png",
        "sell_nook": 3000,
        "location": "Pushing snowballs",
        "weather": "Any weather",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 51,
        "name": "Earth-Boring Dung Beetle",
        "picture": "https://dodo.ac/np/images/1/12/Earth-Boring_Dung_Beetle_NH.png",
        "icon": "https://dodo.ac/np/images/5/53/Earth-Boring_Dung_Beetle_NH_Icon.png",
        "sell_nook": 300,
        "location": "On the ground",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 52,
        "name": "Scarab Beetle",
        "picture": "https://dodo.ac/np/images/d/db/Scarab_Beetle_NH.png",
        "icon": "https://dodo.ac/np/images/e/ee/Scarab_Beetle_NH_Icon.png",
        "sell_nook": 10000,
        "location": "On trees (any kind)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "11 PM \u2013 8 AM"
    },
    {
        "index": 53,
        "name": "Drone Beetle",
        "picture": "https://dodo.ac/np/images/3/3f/Drone_Beetle_NH.png",
        "icon": "https://dodo.ac/np/images/4/48/Drone_Beetle_NH_Icon.png",
        "sell_nook": 200,
        "location": "On trees (any kind)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 54,
        "name": "Goliath Beetle",
        "picture": "https://dodo.ac/np/images/4/43/Goliath_Beetle_NH.png",
        "icon": "https://dodo.ac/np/images/3/3e/Goliath_Beetle_NH_Icon.png",
        "sell_nook": 8000,
        "location": "On palm trees",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "5 PM \u2013 8 AM"
    },
    {
        "index": 55,
        "name": "Saw Stag",
        "picture": "https://dodo.ac/np/images/e/e0/Saw_Stag_NH.png",
        "icon": "https://dodo.ac/np/images/0/03/Saw_Stag_NH_Icon.png",
        "sell_nook": 2000,
        "location": "On trees (any kind)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 56,
        "name": "Miyama Stag",
        "picture": "https://dodo.ac/np/images/5/56/Miyama_Stag_NH.png",
        "icon": "https://dodo.ac/np/images/0/0a/Miyama_Stag_NH_Icon.png",
        "sell_nook": 1000,
        "location": "On trees (any kind)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 57,
        "name": "Giant Stag",
        "picture": "https://dodo.ac/np/images/6/6b/Giant_Stag_NH.png",
        "icon": "https://dodo.ac/np/images/0/08/Giant_Stag_NH_Icon.png",
        "sell_nook": 10000,
        "location": "On trees (any kind)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "11 PM \u2013 8 AM"
    },
    {
        "index": 58,
        "name": "Rainbow Stag",
        "picture": "https://dodo.ac/np/images/8/82/Rainbow_Stag_NH.png",
        "icon": "https://dodo.ac/np/images/f/f7/Rainbow_Stag_NH_Icon.png",
        "sell_nook": 6000,
        "location": "On trees (any kind)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "7 PM \u2013 8 AM"
    },
    {
        "index": 59,
        "name": "Cyclommatus Stag",
        "picture": "https://dodo.ac/np/images/6/64/Cyclommatus_Stag_NH.png",
        "icon": "https://dodo.ac/np/images/a/a0/Cyclommatus_Stag_NH_Icon.png",
        "sell_nook": 8000,
        "location": "On palm trees",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM \u2013 8 AM"
    },
    {
        "index": 60,
        "name": "Golden Stag",
        "picture": "https://dodo.ac/np/images/1/1d/Golden_Stag_NH.png",
        "icon": "https://dodo.ac/np/images/b/ba/Golden_Stag_NH_Icon.png",
        "sell_nook": 12000,
        "location": "On palm trees",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM \u2013 8 AM"
    },
    {
        "index": 61,
        "name": "Giraffe Stag",
        "picture": "https://dodo.ac/np/images/a/a3/Giraffe_Stag_NH.png",
        "icon": "https://dodo.ac/np/images/c/c7/Giraffe_Stag_NH_Icon.png",
        "sell_nook": 12000,
        "location": "On palm trees",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM \u2013 8 AM"
    },
    {
        "index": 62,
        "name": "Horned Dynastid",
        "picture": "https://dodo.ac/np/images/4/4f/Horned_Dynastid_NH.png",
        "icon": "https://dodo.ac/np/images/1/10/Horned_Dynastid_NH_Icon.png",
        "sell_nook": 1350,
        "location": "On trees (any kind)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM \u2013 8 AM"
    },
    {
        "index": 63,
        "name": "Horned Atlas",
        "picture": "https://dodo.ac/np/images/0/06/Horned_Atlas_NH.png",
        "icon": "https://dodo.ac/np/images/2/2a/Horned_Atlas_NH_Icon.png",
        "sell_nook": 8000,
        "location": "On palm trees",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM \u2013 8 AM"
    },
    {
        "index": 64,
        "name": "Horned Elephant",
        "picture": "https://dodo.ac/np/images/b/b9/Horned_Elephant_NH.png",
        "icon": "https://dodo.ac/np/images/e/ea/Horned_Elephant_NH_Icon.png",
        "sell_nook": 8000,
        "location": "On palm trees",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM \u2013 8 AM"
    },
    {
        "index": 65,
        "name": "Horned Hercules",
        "picture": "https://dodo.ac/np/images/4/47/Horned_Hercules_NH.png",
        "icon": "https://dodo.ac/np/images/2/21/Horned_Hercules_NH_Icon.png",
        "sell_nook": 12000,
        "location": "On palm trees",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM \u2013 8 AM"
    },
    {
        "index": 66,
        "name": "Walking Stick",
        "picture": "https://dodo.ac/np/images/0/0f/Walking_Stick_NH.png",
        "icon": "https://dodo.ac/np/images/5/58/Walking_Stick_NH_Icon.png",
        "sell_nook": 600,
        "location": "On trees (any kind)",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 AM \u2013 8 AM &amp; 5 PM \u2013 7 PM"
    },
    {
        "index": 67,
        "name": "Walking Leaf",
        "picture": "https://dodo.ac/np/images/6/6e/Walking_Leaf_NH.png",
        "icon": "https://dodo.ac/np/images/b/b9/Walking_Leaf_NH_Icon.png",
        "sell_nook": 600,
        "location": "Disguised under trees",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 68,
        "name": "Bagworm",
        "picture": "https://dodo.ac/np/images/0/08/Bagworm_NH.png",
        "icon": "https://dodo.ac/np/images/1/17/Bagworm_NH_Icon.png",
        "sell_nook": 600,
        "location": "Shaking trees (hardwood and cedar)",
        "weather": "Any weather",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 69,
        "name": "Ant",
        "picture": "https://dodo.ac/np/images/4/4a/Ant_NH.png",
        "icon": "https://dodo.ac/np/images/5/5d/Ant_NH_Icon.png",
        "sell_nook": 80,
        "location": "On rotten Turnips, Candy, Lollipops",
        "weather": "Any weather",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 70,
        "name": "Hermit Crab",
        "picture": "https://dodo.ac/np/images/8/8f/Hermit_Crab_NH.png",
        "icon": "https://dodo.ac/np/images/6/6b/Hermit_Crab_NH_Icon.png",
        "sell_nook": 1000,
        "location": "Disguised on shoreline",
        "weather": "Any weather",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM \u2013 8 AM"
    },
    {
        "index": 71,
        "name": "Wharf Roach",
        "picture": "https://dodo.ac/np/images/e/eb/Wharf_Roach_NH.png",
        "icon": "https://dodo.ac/np/images/1/1f/Wharf_Roach_NH_Icon.png",
        "sell_nook": 200,
        "location": "On beach rocks",
        "weather": "Any weather",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 72,
        "name": "Fly",
        "picture": "https://dodo.ac/np/images/d/d4/Fly_NH.png",
        "icon": "https://dodo.ac/np/images/1/15/Fly_NH_Icon.png",
        "sell_nook": 60,
        "location": "Flying near trash or rotten turnips",
        "weather": "Any weather",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 73,
        "name": "Mosquito",
        "picture": "https://dodo.ac/np/images/1/1c/Mosquito_NH.png",
        "icon": "https://dodo.ac/np/images/8/84/Mosquito_NH_Icon.png",
        "sell_nook": 130,
        "location": "Flying",
        "weather": "Any except rain",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "5 PM \u2013 4 AM"
    },
    {
        "index": 74,
        "name": "Flea",
        "picture": "https://dodo.ac/np/images/3/3e/Flea_NH.png",
        "icon": "https://dodo.ac/np/images/8/89/Flea_NH_Icon.png",
        "sell_nook": 70,
        "location": "On villagers",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 75,
        "name": "Snail",
        "picture": "https://dodo.ac/np/images/0/0b/Snail_NH.png",
        "icon": "https://dodo.ac/np/images/e/e9/Snail_NH_Icon.png",
        "sell_nook": 250,
        "location": "On rocks and bushes",
        "weather": "Rain only",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 76,
        "name": "Pill Bug",
        "picture": "https://dodo.ac/np/images/0/02/Pill_Bug_NH.png",
        "icon": "https://dodo.ac/np/images/b/b9/Pill_Bug_NH_Icon.png",
        "sell_nook": 250,
        "location": "From hitting rocks",
        "weather": "Any weather",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "11 PM \u2013 4 PM"
    },
    {
        "index": 77,
        "name": "Centipede",
        "picture": "https://dodo.ac/np/images/8/89/Centipede_NH.png",
        "icon": "https://dodo.ac/np/images/d/d2/Centipede_NH_Icon.png",
        "sell_nook": 300,
        "location": "From hitting rocks",
        "weather": "Any weather",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM \u2013 11 PM"
    },
    {
        "index": 78,
        "name": "Spider",
        "picture": "https://dodo.ac/np/images/e/e5/Spider_NH.png",
        "icon": "https://dodo.ac/np/images/e/e0/Spider_NH_Icon.png",
        "sell_nook": 600,
        "location": "Shaking trees",
        "weather": "Any weather",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM \u2013 8 AM"
    },
    {
        "index": 79,
        "name": "Tarantula",
        "picture": "https://dodo.ac/np/images/b/bf/Tarantula_NH.png",
        "icon": "https://dodo.ac/np/images/b/b5/Tarantula_NH_Icon.png",
        "sell_nook": 8000,
        "location": "On the ground",
        "weather": "Any weather",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 0,
        "s_m12": 0,
        "time": "7 PM \u2013 4 AM"
    },
    {
        "index": 80,
        "name": "Scorpion",
        "picture": "https://dodo.ac/np/images/f/fe/Scorpion_NH.png",
        "icon": "https://dodo.ac/np/images/9/95/Scorpion_NH_Icon.png",
        "sell_nook": 8000,
        "location": "On the ground",
        "weather": "Any weather",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM \u2013 4 AM"
    }
]