//https://nookipedia.com/w/index.php?title=Special%3ACargoQuery&tables=nh_sea_creature%2C+&fields=nh_sea_creature.number+%3D+index%2C+nh_sea_creature.name%2C+nh_sea_creature.render_url+%3D+picture%2C+nh_sea_creature.image_url+%3D+icon%2C+nh_sea_creature.sell_nook%2C+nh_sea_creature.shadow_size%2C+nh_sea_creature.shadow_movement%2C+nh_sea_creature.n_m1%2C+nh_sea_creature.n_m2%2C+nh_sea_creature.n_m3%2C+nh_sea_creature.n_m4%2C+nh_sea_creature.n_m5%2C+nh_sea_creature.n_m6%2C+nh_sea_creature.n_m7%2C+nh_sea_creature.n_m8%2C+nh_sea_creature.n_m9%2C+nh_sea_creature.n_m10%2C+nh_sea_creature.n_m11%2C+nh_sea_creature.n_m12%2C+nh_sea_creature.s_m1%2C+nh_sea_creature.s_m2%2C+nh_sea_creature.s_m3%2C+nh_sea_creature.s_m4%2C+nh_sea_creature.s_m5%2C+nh_sea_creature.s_m6%2C+nh_sea_creature.s_m7%2C+nh_sea_creature.s_m8%2C+nh_sea_creature.s_m9%2C+nh_sea_creature.s_m10%2C+nh_sea_creature.s_m11%2C+nh_sea_creature.s_m12%2C+nh_sea_creature.time%2C+&where=&join_on=&group_by=&having=&order_by%5B0%5D=&order_by_options%5B0%5D=ASC&limit=1000&offset=0&format=
const divingArr = 
[
    {
        "index": 1,
        "name": "Seaweed",
        "picture": "https://dodo.ac/np/images/c/c3/Seaweed_NH.png",
        "icon": "https://dodo.ac/np/images/8/8c/Seaweed_NH_Icon.png",
        "sell_nook": 600,
        "shadow_size": "Large",
        "shadow_movement": "Stationary",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 2,
        "name": "Sea Grapes",
        "picture": "https://dodo.ac/np/images/5/56/Sea_Grapes_NH.png",
        "icon": "https://dodo.ac/np/images/e/e7/Sea_Grapes_NH_Icon.png",
        "sell_nook": 900,
        "shadow_size": "Small",
        "shadow_movement": "Stationary",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 3,
        "name": "Sea Cucumber",
        "picture": "https://dodo.ac/np/images/4/43/Sea_Cucumber_NH.png",
        "icon": "https://dodo.ac/np/images/9/9b/Sea_Cucumber_NH_Icon.png",
        "sell_nook": 500,
        "shadow_size": "Medium",
        "shadow_movement": "Very slow",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 4,
        "name": "Sea Pig",
        "picture": "https://dodo.ac/np/images/a/a3/Sea_Pig_NH.png",
        "icon": "https://dodo.ac/np/images/a/a9/Sea_Pig_NH_Icon.png",
        "sell_nook": 10000,
        "shadow_size": "Small",
        "shadow_movement": "Very fast",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 PM \u2013\u00a09 AM"
    },
    {
        "index": 5,
        "name": "Sea Star",
        "picture": "https://dodo.ac/np/images/f/f8/Sea_Star_NH.png",
        "icon": "https://dodo.ac/np/images/6/6c/Sea_Star_NH_Icon.png",
        "sell_nook": 500,
        "shadow_size": "Small",
        "shadow_movement": "Very slow",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 6,
        "name": "Sea Urchin",
        "picture": "https://dodo.ac/np/images/7/7e/Sea_Urchin_NH.png",
        "icon": "https://dodo.ac/np/images/9/9c/Sea_Urchin_NH_Icon.png",
        "sell_nook": 1700,
        "shadow_size": "Small",
        "shadow_movement": "Slow",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 7,
        "name": "Slate Pencil Urchin",
        "picture": "https://dodo.ac/np/images/f/f5/Slate_Pencil_Urchin_NH.png",
        "icon": "https://dodo.ac/np/images/0/05/Slate_Pencil_Urchin_NH_Icon.png",
        "sell_nook": 2000,
        "shadow_size": "Medium",
        "shadow_movement": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM \u2013\u00a09 AM"
    },
    {
        "index": 8,
        "name": "Sea Anemone",
        "picture": "https://dodo.ac/np/images/0/01/Sea_Anemone_NH.png",
        "icon": "https://dodo.ac/np/images/e/e9/Sea_Anemone_NH_Icon.png",
        "sell_nook": 500,
        "shadow_size": "Large",
        "shadow_movement": "Stationary",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 9,
        "name": "Moon Jellyfish",
        "picture": "https://dodo.ac/np/images/f/f5/Moon_Jellyfish_NH.png",
        "icon": "https://dodo.ac/np/images/f/f9/Moon_Jellyfish_NH_Icon.png",
        "sell_nook": 600,
        "shadow_size": "Small",
        "shadow_movement": "Very slow",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 10,
        "name": "Sea Slug",
        "picture": "https://dodo.ac/np/images/4/49/Sea_Slug_NH.png",
        "icon": "https://dodo.ac/np/images/5/54/Sea_Slug_NH_Icon.png",
        "sell_nook": 600,
        "shadow_size": "Tiny",
        "shadow_movement": "Very slow",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 11,
        "name": "Pearl Oyster",
        "picture": "https://dodo.ac/np/images/5/52/Pearl_Oyster_NH.png",
        "icon": "https://dodo.ac/np/images/0/0a/Pearl_Oyster_NH_Icon.png",
        "sell_nook": 2800,
        "shadow_size": "Small",
        "shadow_movement": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 12,
        "name": "Mussel",
        "picture": "https://dodo.ac/np/images/a/a9/Mussel_NH.png",
        "icon": "https://dodo.ac/np/images/6/6c/Mussel_NH_Icon.png",
        "sell_nook": 1500,
        "shadow_size": "Small",
        "shadow_movement": "Slow",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 13,
        "name": "Oyster",
        "picture": "https://dodo.ac/np/images/6/66/Oyster_NH.png",
        "icon": "https://dodo.ac/np/images/4/4d/Oyster_NH_Icon.png",
        "sell_nook": 1100,
        "shadow_size": "Small",
        "shadow_movement": "Slow",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 14,
        "name": "Scallop",
        "picture": "https://dodo.ac/np/images/4/4a/Scallop_NH.png",
        "icon": "https://dodo.ac/np/images/5/55/Scallop_NH_Icon.png",
        "sell_nook": 1200,
        "shadow_size": "Medium",
        "shadow_movement": "Slow",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 15,
        "name": "Whelk",
        "picture": "https://dodo.ac/np/images/5/54/Whelk_NH.png",
        "icon": "https://dodo.ac/np/images/5/5e/Whelk_NH_Icon.png",
        "sell_nook": 1000,
        "shadow_size": "Small",
        "shadow_movement": "Slow",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 16,
        "name": "Turban Shell",
        "picture": "https://dodo.ac/np/images/6/63/Turban_Shell_NH.png",
        "icon": "https://dodo.ac/np/images/9/93/Turban_Shell_NH_Icon.png",
        "sell_nook": 1000,
        "shadow_size": "Small",
        "shadow_movement": "Slow",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 17,
        "name": "Abalone",
        "picture": "https://dodo.ac/np/images/f/fd/Abalone_NH.png",
        "icon": "https://dodo.ac/np/images/0/04/Abalone_NH_Icon.png",
        "sell_nook": 2000,
        "shadow_size": "Medium",
        "shadow_movement": "Medium",
        "n_m1": 1,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM \u2013\u00a09 AM"
    },
    {
        "index": 18,
        "name": "Gigas Giant Clam",
        "picture": "https://dodo.ac/np/images/1/17/Gigas_Giant_Clam_NH.png",
        "icon": "https://dodo.ac/np/images/c/ca/Gigas_Giant_Clam_NH_Icon.png",
        "sell_nook": 15000,
        "shadow_size": "Very large",
        "shadow_movement": "Very fast",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 19,
        "name": "Chambered Nautilus",
        "picture": "https://dodo.ac/np/images/4/4a/Chambered_Nautilus_NH.png",
        "icon": "https://dodo.ac/np/images/9/98/Chambered_Nautilus_NH_Icon.png",
        "sell_nook": 1800,
        "shadow_size": "Medium",
        "shadow_movement": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM \u2013\u00a09 AM"
    },
    {
        "index": 20,
        "name": "Octopus",
        "picture": "https://dodo.ac/np/images/2/27/Octopus_NH.png",
        "icon": "https://dodo.ac/np/images/5/58/Octopus_NH_Icon.png",
        "sell_nook": 1200,
        "shadow_size": "Medium",
        "shadow_movement": "Slow",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 21,
        "name": "Umbrella Octopus",
        "picture": "https://dodo.ac/np/images/c/c0/Umbrella_Octopus_NH.png",
        "icon": "https://dodo.ac/np/images/a/ac/Umbrella_Octopus_NH_Icon.png",
        "sell_nook": 6000,
        "shadow_size": "Small",
        "shadow_movement": "Fast",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 22,
        "name": "Vampire Squid",
        "picture": "https://dodo.ac/np/images/0/0d/Vampire_Squid_NH.png",
        "icon": "https://dodo.ac/np/images/a/ac/Vampire_Squid_NH_Icon.png",
        "sell_nook": 10000,
        "shadow_size": "Medium",
        "shadow_movement": "Very fast",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM \u2013\u00a09 AM"
    },
    {
        "index": 23,
        "name": "Firefly Squid",
        "picture": "https://dodo.ac/np/images/7/71/Firefly_Squid_NH.png",
        "icon": "https://dodo.ac/np/images/d/d0/Firefly_Squid_NH_Icon.png",
        "sell_nook": 1400,
        "shadow_size": "Tiny",
        "shadow_movement": "Slow",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 PM \u2013\u00a04 AM"
    },
    {
        "index": 24,
        "name": "Gazami Crab",
        "picture": "https://dodo.ac/np/images/8/80/Gazami_Crab_NH.png",
        "icon": "https://dodo.ac/np/images/6/60/Gazami_Crab_NH_Icon.png",
        "sell_nook": 2200,
        "shadow_size": "Medium",
        "shadow_movement": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 25,
        "name": "Dungeness Crab",
        "picture": "https://dodo.ac/np/images/6/67/Dungeness_Crab_NH.png",
        "icon": "https://dodo.ac/np/images/6/65/Dungeness_Crab_NH_Icon.png",
        "sell_nook": 1900,
        "shadow_size": "Medium",
        "shadow_movement": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 26,
        "name": "Snow Crab",
        "picture": "https://dodo.ac/np/images/c/c0/Snow_Crab_NH.png",
        "icon": "https://dodo.ac/np/images/7/78/Snow_Crab_NH_Icon.png",
        "sell_nook": 6000,
        "shadow_size": "Large",
        "shadow_movement": "Fast",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 27,
        "name": "Red King Crab",
        "picture": "https://dodo.ac/np/images/c/cf/Red_King_Crab_NH.png",
        "icon": "https://dodo.ac/np/images/9/9d/Red_King_Crab_NH_Icon.png",
        "sell_nook": 8000,
        "shadow_size": "Large",
        "shadow_movement": "Very fast",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 28,
        "name": "Acorn Barnacle",
        "picture": "https://dodo.ac/np/images/d/d8/Acorn_Barnacle_NH.png",
        "icon": "https://dodo.ac/np/images/a/a4/Acorn_Barnacle_NH_Icon.png",
        "sell_nook": 600,
        "shadow_size": "Tiny",
        "shadow_movement": "Stationary",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 29,
        "name": "Spider Crab",
        "picture": "https://dodo.ac/np/images/c/cc/Spider_Crab_NH.png",
        "icon": "https://dodo.ac/np/images/f/f3/Spider_Crab_NH_Icon.png",
        "sell_nook": 12000,
        "shadow_size": "Very large",
        "shadow_movement": "Very fast",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 30,
        "name": "Tiger Prawn",
        "picture": "https://dodo.ac/np/images/7/72/Tiger_Prawn_NH.png",
        "icon": "https://dodo.ac/np/images/6/65/Tiger_Prawn_NH_Icon.png",
        "sell_nook": 3000,
        "shadow_size": "Small",
        "shadow_movement": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM \u2013\u00a09 AM"
    },
    {
        "index": 31,
        "name": "Sweet Shrimp",
        "picture": "https://dodo.ac/np/images/8/80/Sweet_Shrimp_NH.png",
        "icon": "https://dodo.ac/np/images/d/d3/Sweet_Shrimp_NH_Icon.png",
        "sell_nook": 1400,
        "shadow_size": "Small",
        "shadow_movement": "Slow",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 PM \u2013\u00a09 AM"
    },
    {
        "index": 32,
        "name": "Mantis Shrimp",
        "picture": "https://dodo.ac/np/images/b/b5/Mantis_Shrimp_NH.png",
        "icon": "https://dodo.ac/np/images/7/7d/Mantis_Shrimp_NH_Icon.png",
        "sell_nook": 2500,
        "shadow_size": "Small",
        "shadow_movement": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM \u2013\u00a09 AM"
    },
    {
        "index": 33,
        "name": "Spiny Lobster",
        "picture": "https://dodo.ac/np/images/3/3d/Spiny_Lobster_NH.png",
        "icon": "https://dodo.ac/np/images/8/8c/Spiny_Lobster_NH_Icon.png",
        "sell_nook": 5000,
        "shadow_size": "Large",
        "shadow_movement": "Fast",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "9 PM \u2013\u00a04 AM"
    },
    {
        "index": 34,
        "name": "Lobster",
        "picture": "https://dodo.ac/np/images/b/b6/Lobster_NH.png",
        "icon": "https://dodo.ac/np/images/a/a9/Lobster_NH_Icon.png",
        "sell_nook": 4500,
        "shadow_size": "Large",
        "shadow_movement": "Fast",
        "n_m1": 1,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 35,
        "name": "Giant Isopod",
        "picture": "https://dodo.ac/np/images/5/58/Giant_Isopod_NH.png",
        "icon": "https://dodo.ac/np/images/0/00/Giant_Isopod_NH_Icon.png",
        "sell_nook": 12000,
        "shadow_size": "Medium",
        "shadow_movement": "Very fast",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "9 AM \u2013\u00a04 PM; 9 PM \u2013 4 AM"
    },
    {
        "index": 36,
        "name": "Horseshoe Crab",
        "picture": "https://dodo.ac/np/images/8/86/Horseshoe_Crab_NH.png",
        "icon": "https://dodo.ac/np/images/5/5b/Horseshoe_Crab_NH_Icon.png",
        "sell_nook": 2500,
        "shadow_size": "Medium",
        "shadow_movement": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "9 PM \u2013\u00a04 AM"
    },
    {
        "index": 37,
        "name": "Sea Pineapple",
        "picture": "https://dodo.ac/np/images/4/41/Sea_Pineapple_NH.png",
        "icon": "https://dodo.ac/np/images/6/61/Sea_Pineapple_NH_Icon.png",
        "sell_nook": 1500,
        "shadow_size": "Small",
        "shadow_movement": "Slow",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 38,
        "name": "Spotted Garden Eel",
        "picture": "https://dodo.ac/np/images/d/df/Spotted_Garden_Eel_NH.png",
        "icon": "https://dodo.ac/np/images/a/aa/Spotted_Garden_Eel_NH_Icon.png",
        "sell_nook": 1100,
        "shadow_size": "Small",
        "shadow_movement": "Slow",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM \u2013 9 PM"
    },
    {
        "index": 39,
        "name": "Flatworm",
        "picture": "https://dodo.ac/np/images/a/a4/Flatworm_NH.png",
        "icon": "https://dodo.ac/np/images/0/07/Flatworm_NH_Icon.png",
        "sell_nook": 700,
        "shadow_size": "Tiny",
        "shadow_movement": "Very slow",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 PM \u2013\u00a09 AM"
    },
    {
        "index": 40,
        "name": "Venus Flower Basket",
        "picture": "https://dodo.ac/np/images/5/51/Venus%27_Flower_Basket_NH.png",
        "icon": "https://dodo.ac/np/images/6/6a/Venus%27_Flower_Basket_NH_Icon.png",
        "sell_nook": 5000,
        "shadow_size": "Medium",
        "shadow_movement": "Fast",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    }
]