//https://nookipedia.com/w/index.php?title=Special%3ACargoQuery&tables=nh_fish%2C+&fields=nh_fish.number+%3D+index%2C+nh_fish.name%2C+nh_fish.render_url+%3D+picture%2C+nh_fish.image_url+%3D+icon%2C+nh_fish.sell_nook%2C+nh_fish.location%2C+nh_fish.shadow_size%2C+nh_fish.n_m1%2C+nh_fish.n_m2%2C+nh_fish.n_m3%2C+nh_fish.n_m4%2C+nh_fish.n_m5%2C+nh_fish.n_m6%2C+nh_fish.n_m7%2C+nh_fish.n_m8%2C+nh_fish.n_m9%2C+nh_fish.n_m10%2C+nh_fish.n_m11%2C+nh_fish.n_m12%2C+nh_fish.s_m1%2C+nh_fish.s_m2%2C+nh_fish.s_m3%2C+nh_fish.s_m4%2C+nh_fish.s_m5%2C+nh_fish.s_m6%2C+nh_fish.s_m7%2C+nh_fish.s_m8%2C+nh_fish.s_m9%2C+nh_fish.s_m10%2C+nh_fish.s_m11%2C+nh_fish.s_m12%2C+nh_fish.time%2C+&where=&join_on=&group_by=&having=&order_by%5B0%5D=&order_by_options%5B0%5D=ASC&limit=1000&offset=0&format=
const fishArr =
[
    {
        "index": 1,
        "name": "Bitterling",
        "picture": "https://dodo.ac/np/images/8/86/Bitterling_NH.png",
        "icon": "https://dodo.ac/np/images/4/4d/Bitterling_NH_Icon.png",
        "sell_nook": 900,
        "location": "River",
        "shadow_size": "Tiny",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 2,
        "name": "Pale Chub",
        "picture": "https://dodo.ac/np/images/8/8a/Pale_Chub_NH.png",
        "icon": "https://dodo.ac/np/images/e/e2/Pale_Chub_NH_Icon.png",
        "sell_nook": 200,
        "location": "River",
        "shadow_size": "Tiny",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM \u2013 4 PM"
    },
    {
        "index": 3,
        "name": "Crucian Carp",
        "picture": "https://dodo.ac/np/images/5/5c/Crucian_Carp_NH.png",
        "icon": "https://dodo.ac/np/images/f/f2/Crucian_Carp_NH_Icon.png",
        "sell_nook": 160,
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 4,
        "name": "Dace",
        "picture": "https://dodo.ac/np/images/3/34/Dace_NH.png",
        "icon": "https://dodo.ac/np/images/d/db/Dace_NH_Icon.png",
        "sell_nook": 240,
        "location": "River",
        "shadow_size": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 5,
        "name": "Carp",
        "picture": "https://dodo.ac/np/images/3/39/Carp_NH.png",
        "icon": "https://dodo.ac/np/images/5/5d/Carp_NH_Icon.png",
        "sell_nook": 300,
        "location": "Pond",
        "shadow_size": "Large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 6,
        "name": "Koi",
        "picture": "https://dodo.ac/np/images/2/24/Koi_NH.png",
        "icon": "https://dodo.ac/np/images/2/2d/Koi_NH_Icon.png",
        "sell_nook": 4000,
        "location": "Pond",
        "shadow_size": "Large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 7,
        "name": "Goldfish",
        "picture": "https://dodo.ac/np/images/e/e7/Goldfish_NH.png",
        "icon": "https://dodo.ac/np/images/7/71/Goldfish_NH_Icon.png",
        "sell_nook": 1300,
        "location": "Pond",
        "shadow_size": "Tiny",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 8,
        "name": "Pop-Eyed Goldfish",
        "picture": "https://dodo.ac/np/images/8/8a/Pop-Eyed_Goldfish_NH.png",
        "icon": "https://dodo.ac/np/images/0/0d/Pop-Eyed_Goldfish_NH_Icon.png",
        "sell_nook": 1300,
        "location": "Pond",
        "shadow_size": "Tiny",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM \u2013 4 PM"
    },
    {
        "index": 9,
        "name": "Ranchu Goldfish",
        "picture": "https://dodo.ac/np/images/4/41/Ranchu_Goldfish_NH.png",
        "icon": "https://dodo.ac/np/images/3/35/Ranchu_Goldfish_NH_Icon.png",
        "sell_nook": 4500,
        "location": "Pond",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM \u2013 4 PM"
    },
    {
        "index": 10,
        "name": "Killifish",
        "picture": "https://dodo.ac/np/images/c/c2/Killifish_NH.png",
        "icon": "https://dodo.ac/np/images/e/ea/Killifish_NH_Icon.png",
        "sell_nook": 300,
        "location": "Pond",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 11,
        "name": "Crawfish",
        "picture": "https://dodo.ac/np/images/b/b6/Crawfish_NH.png",
        "icon": "https://dodo.ac/np/images/9/96/Crawfish_NH_Icon.png",
        "sell_nook": 200,
        "location": "Pond",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 12,
        "name": "Soft-Shelled Turtle",
        "picture": "https://dodo.ac/np/images/9/98/Soft-Shelled_Turtle_NH.png",
        "icon": "https://dodo.ac/np/images/e/eb/Soft-Shelled_Turtle_NH_Icon.png",
        "sell_nook": 3750,
        "location": "River",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 13,
        "name": "Snapping Turtle",
        "picture": "https://dodo.ac/np/images/9/90/Snapping_Turtle_NH.png",
        "icon": "https://dodo.ac/np/images/b/b1/Snapping_Turtle_NH_Icon.png",
        "sell_nook": 5000,
        "location": "River",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 PM \u2013 4 AM"
    },
    {
        "index": 14,
        "name": "Tadpole",
        "picture": "https://dodo.ac/np/images/9/9f/Tadpole_NH.png",
        "icon": "https://dodo.ac/np/images/b/bb/Tadpole_NH_Icon.png",
        "sell_nook": 100,
        "location": "Pond",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 15,
        "name": "Frog",
        "picture": "https://dodo.ac/np/images/b/b7/Frog_NH.png",
        "icon": "https://dodo.ac/np/images/2/2f/Frog_NH_Icon.png",
        "sell_nook": 120,
        "location": "Pond",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 16,
        "name": "Freshwater Goby",
        "picture": "https://dodo.ac/np/images/5/5a/Freshwater_Goby_NH.png",
        "icon": "https://dodo.ac/np/images/e/ec/Freshwater_Goby_NH_Icon.png",
        "sell_nook": 400,
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 17,
        "name": "Loach",
        "picture": "https://dodo.ac/np/images/4/4f/Loach_NH.png",
        "icon": "https://dodo.ac/np/images/a/a5/Loach_NH_Icon.png",
        "sell_nook": 400,
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 18,
        "name": "Catfish",
        "picture": "https://dodo.ac/np/images/3/32/Catfish_NH.png",
        "icon": "https://dodo.ac/np/images/0/0d/Catfish_NH_Icon.png",
        "sell_nook": 800,
        "location": "Pond",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM - 9 AM"
    },
    {
        "index": 19,
        "name": "Giant Snakehead",
        "picture": "https://dodo.ac/np/images/2/29/Giant_Snakehead_NH.png",
        "icon": "https://dodo.ac/np/images/5/50/Giant_Snakehead_NH_Icon.png",
        "sell_nook": 5500,
        "location": "Pond",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "9 AM \u2013 4 PM"
    },
    {
        "index": 20,
        "name": "Bluegill",
        "picture": "https://dodo.ac/np/images/0/05/Bluegill_NH.png",
        "icon": "https://dodo.ac/np/images/0/0c/Bluegill_NH_Icon.png",
        "sell_nook": 180,
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM \u2013 4 PM"
    },
    {
        "index": 21,
        "name": "Yellow Perch",
        "picture": "https://dodo.ac/np/images/c/cf/Yellow_Perch_NH.png",
        "icon": "https://dodo.ac/np/images/6/67/Yellow_Perch_NH_Icon.png",
        "sell_nook": 300,
        "location": "River",
        "shadow_size": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 22,
        "name": "Black Bass",
        "picture": "https://dodo.ac/np/images/4/4b/Black_Bass_NH.png",
        "icon": "https://dodo.ac/np/images/0/00/Black_Bass_NH_Icon.png",
        "sell_nook": 400,
        "location": "River",
        "shadow_size": "Large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 23,
        "name": "Tilapia",
        "picture": "https://dodo.ac/np/images/7/71/Tilapia_NH.png",
        "icon": "https://dodo.ac/np/images/e/ef/Tilapia_NH_Icon.png",
        "sell_nook": 800,
        "location": "River",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 24,
        "name": "Pike",
        "picture": "https://dodo.ac/np/images/8/89/Pike_NH.png",
        "icon": "https://dodo.ac/np/images/9/9f/Pike_NH_Icon.png",
        "sell_nook": 1800,
        "location": "River",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 25,
        "name": "Pond Smelt",
        "picture": "https://dodo.ac/np/images/f/fc/Pond_Smelt_NH.png",
        "icon": "https://dodo.ac/np/images/0/0f/Pond_Smelt_NH_Icon.png",
        "sell_nook": 400,
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 26,
        "name": "Sweetfish",
        "picture": "https://dodo.ac/np/images/9/93/Sweetfish_NH.png",
        "icon": "https://dodo.ac/np/images/6/6a/Sweetfish_NH_Icon.png",
        "sell_nook": 900,
        "location": "River",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 27,
        "name": "Cherry Salmon",
        "picture": "https://dodo.ac/np/images/c/c0/Cherry_Salmon_NH.png",
        "icon": "https://dodo.ac/np/images/d/db/Cherry_Salmon_NH_Icon.png",
        "sell_nook": 1000,
        "location": "River (clifftop)",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 28,
        "name": "Char",
        "picture": "https://dodo.ac/np/images/0/0f/Char_NH.png",
        "icon": "https://dodo.ac/np/images/8/80/Char_NH_Icon.png",
        "sell_nook": 3800,
        "location": "River (clifftop)",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 29,
        "name": "Golden Trout",
        "picture": "https://dodo.ac/np/images/a/af/Golden_Trout_NH.png",
        "icon": "https://dodo.ac/np/images/f/fc/Golden_Trout_NH_Icon.png",
        "sell_nook": 15000,
        "location": "River (clifftop)",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 0,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 30,
        "name": "Stringfish",
        "picture": "https://dodo.ac/np/images/b/bf/Stringfish_NH.png",
        "icon": "https://dodo.ac/np/images/e/eb/Stringfish_NH_Icon.png",
        "sell_nook": 15000,
        "location": "River (clifftop)",
        "shadow_size": "Very large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 31,
        "name": "Salmon",
        "picture": "https://dodo.ac/np/images/8/85/Salmon_NH.png",
        "icon": "https://dodo.ac/np/images/c/ca/Salmon_NH_Icon.png",
        "sell_nook": 700,
        "location": "River (mouth)",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 32,
        "name": "King Salmon",
        "picture": "https://dodo.ac/np/images/d/d8/King_Salmon_NH.png",
        "icon": "https://dodo.ac/np/images/e/e1/King_Salmon_NH_Icon.png",
        "sell_nook": 1800,
        "location": "River (mouth)",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 33,
        "name": "Mitten Crab",
        "picture": "https://dodo.ac/np/images/4/40/Mitten_Crab_NH.png",
        "icon": "https://dodo.ac/np/images/9/9d/Mitten_Crab_NH_Icon.png",
        "sell_nook": 2000,
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 34,
        "name": "Guppy",
        "picture": "https://dodo.ac/np/images/d/d7/Guppy_NH.png",
        "icon": "https://dodo.ac/np/images/3/38/Guppy_NH_Icon.png",
        "sell_nook": 1300,
        "location": "River",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM \u2013 4 PM"
    },
    {
        "index": 35,
        "name": "Nibble Fish",
        "picture": "https://dodo.ac/np/images/9/96/Nibble_Fish_NH.png",
        "icon": "https://dodo.ac/np/images/0/0b/Nibble_Fish_NH_Icon.png",
        "sell_nook": 1500,
        "location": "River",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM \u2013 4 PM"
    },
    {
        "index": 36,
        "name": "Angelfish",
        "picture": "https://dodo.ac/np/images/6/69/Angelfish_NH.png",
        "icon": "https://dodo.ac/np/images/c/cd/Angelfish_NH_Icon.png",
        "sell_nook": 3000,
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 37,
        "name": "Betta",
        "picture": "https://dodo.ac/np/images/7/7f/Betta_NH.png",
        "icon": "https://dodo.ac/np/images/0/0b/Betta_NH_Icon.png",
        "sell_nook": 2500,
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM \u2013 4 PM"
    },
    {
        "index": 38,
        "name": "Neon Tetra",
        "picture": "https://dodo.ac/np/images/e/e8/Neon_Tetra_NH.png",
        "icon": "https://dodo.ac/np/images/4/42/Neon_Tetra_NH_Icon.png",
        "sell_nook": 500,
        "location": "River",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM \u2013 4 PM"
    },
    {
        "index": 39,
        "name": "Rainbowfish",
        "picture": "https://dodo.ac/np/images/3/36/Rainbowfish_NH.png",
        "icon": "https://dodo.ac/np/images/e/e7/Rainbowfish_NH_Icon.png",
        "sell_nook": 800,
        "location": "River",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM \u2013 4 PM"
    },
    {
        "index": 40,
        "name": "Piranha",
        "picture": "https://dodo.ac/np/images/f/fa/Piranha_NH.png",
        "icon": "https://dodo.ac/np/images/c/c6/Piranha_NH_Icon.png",
        "sell_nook": 2500,
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "9 AM \u2013 4 PM &amp; 9 PM \u2013 4 AM"
    },
    {
        "index": 41,
        "name": "Arowana",
        "picture": "https://dodo.ac/np/images/9/9a/Arowana_NH.png",
        "icon": "https://dodo.ac/np/images/6/67/Arowana_NH_Icon.png",
        "sell_nook": 10000,
        "location": "River",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 42,
        "name": "Dorado",
        "picture": "https://dodo.ac/np/images/2/2f/Dorado_NH.png",
        "icon": "https://dodo.ac/np/images/f/fe/Dorado_NH_Icon.png",
        "sell_nook": 15000,
        "location": "River",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 AM \u2013 9 PM"
    },
    {
        "index": 43,
        "name": "Gar",
        "picture": "https://dodo.ac/np/images/c/c8/Gar_NH.png",
        "icon": "https://dodo.ac/np/images/a/a2/Gar_NH_Icon.png",
        "sell_nook": 6000,
        "location": "Pond",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 44,
        "name": "Arapaima",
        "picture": "https://dodo.ac/np/images/8/89/Arapaima_NH.png",
        "icon": "https://dodo.ac/np/images/b/b1/Arapaima_NH_Icon.png",
        "sell_nook": 10000,
        "location": "River",
        "shadow_size": "Huge",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 45,
        "name": "Saddled Bichir",
        "picture": "https://dodo.ac/np/images/c/c6/Saddled_Bichir_NH.png",
        "icon": "https://dodo.ac/np/images/4/46/Saddled_Bichir_NH_Icon.png",
        "sell_nook": 4000,
        "location": "River",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "9 PM \u2013 4 AM"
    },
    {
        "index": 46,
        "name": "Sturgeon",
        "picture": "https://dodo.ac/np/images/1/1c/Sturgeon_NH.png",
        "icon": "https://dodo.ac/np/images/9/91/Sturgeon_NH_Icon.png",
        "sell_nook": 10000,
        "location": "River (mouth)",
        "shadow_size": "Huge",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 47,
        "name": "Sea Butterfly",
        "picture": "https://dodo.ac/np/images/f/f9/Sea_Butterfly_NH.png",
        "icon": "https://dodo.ac/np/images/f/f7/Sea_Butterfly_NH_Icon.png",
        "sell_nook": 1000,
        "location": "Sea",
        "shadow_size": "Tiny",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 48,
        "name": "Sea Horse",
        "picture": "https://dodo.ac/np/images/7/7f/Sea_Horse_NH.png",
        "icon": "https://dodo.ac/np/images/d/dc/Sea_Horse_NH_Icon.png",
        "sell_nook": 1100,
        "location": "Sea",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 49,
        "name": "Clown Fish",
        "picture": "https://dodo.ac/np/images/9/94/Clown_Fish_NH.png",
        "icon": "https://dodo.ac/np/images/4/4f/Clown_Fish_NH_Icon.png",
        "sell_nook": 650,
        "location": "Sea",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 50,
        "name": "Surgeonfish",
        "picture": "https://dodo.ac/np/images/6/6a/Surgeonfish_NH.png",
        "icon": "https://dodo.ac/np/images/c/cb/Surgeonfish_NH_Icon.png",
        "sell_nook": 1000,
        "location": "Sea",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 51,
        "name": "Butterfly Fish",
        "picture": "https://dodo.ac/np/images/e/ef/Butterfly_Fish_NH.png",
        "icon": "https://dodo.ac/np/images/4/47/Butterfly_Fish_NH_Icon.png",
        "sell_nook": 1000,
        "location": "Sea",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 52,
        "name": "Napoleonfish",
        "picture": "https://dodo.ac/np/images/6/62/Napoleonfish_NH.png",
        "icon": "https://dodo.ac/np/images/3/30/Napoleonfish_NH_Icon.png",
        "sell_nook": 10000,
        "location": "Sea",
        "shadow_size": "Huge",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 AM \u2013 9 PM"
    },
    {
        "index": 53,
        "name": "Zebra Turkeyfish",
        "picture": "https://dodo.ac/np/images/8/8d/Zebra_Turkeyfish_NH.png",
        "icon": "https://dodo.ac/np/images/8/85/Zebra_Turkeyfish_NH_Icon.png",
        "sell_nook": 500,
        "location": "Sea",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 54,
        "name": "Blowfish",
        "picture": "https://dodo.ac/np/images/2/29/Blowfish_NH.png",
        "icon": "https://dodo.ac/np/images/9/95/Blowfish_NH_Icon.png",
        "sell_nook": 5000,
        "location": "Sea",
        "shadow_size": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "9 PM \u2013 4 AM"
    },
    {
        "index": 55,
        "name": "Puffer Fish",
        "picture": "https://dodo.ac/np/images/1/11/Puffer_Fish_NH.png",
        "icon": "https://dodo.ac/np/images/e/ee/Puffer_Fish_NH_Icon.png",
        "sell_nook": 250,
        "location": "Sea",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 56,
        "name": "Anchovy",
        "picture": "https://dodo.ac/np/images/1/19/Anchovy_%28Fish%29_NH.png",
        "icon": "https://dodo.ac/np/images/7/7f/Anchovy_%28Fish%29_NH_Icon.png",
        "sell_nook": 200,
        "location": "Sea",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM \u2013 9 PM"
    },
    {
        "index": 57,
        "name": "Horse Mackerel",
        "picture": "https://dodo.ac/np/images/7/77/Horse_Mackerel_NH.png",
        "icon": "https://dodo.ac/np/images/a/a3/Horse_Mackerel_NH_Icon.png",
        "sell_nook": 150,
        "location": "Sea",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 58,
        "name": "Barred Knifejaw",
        "picture": "https://dodo.ac/np/images/1/17/Barred_Knifejaw_NH.png",
        "icon": "https://dodo.ac/np/images/d/d5/Barred_Knifejaw_NH_Icon.png",
        "sell_nook": 5000,
        "location": "Sea",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 59,
        "name": "Sea Bass",
        "picture": "https://dodo.ac/np/images/d/d6/Sea_Bass_NH.png",
        "icon": "https://dodo.ac/np/images/7/7f/Sea_Bass_NH_Icon.png",
        "sell_nook": 400,
        "location": "Sea",
        "shadow_size": "Very large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 60,
        "name": "Red Snapper",
        "picture": "https://dodo.ac/np/images/1/13/Red_Snapper_NH.png",
        "icon": "https://dodo.ac/np/images/c/c1/Red_Snapper_NH_Icon.png",
        "sell_nook": 3000,
        "location": "Sea",
        "shadow_size": "Large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 61,
        "name": "Dab",
        "picture": "https://dodo.ac/np/images/e/e0/Dab_NH.png",
        "icon": "https://dodo.ac/np/images/1/1f/Dab_NH_Icon.png",
        "sell_nook": 300,
        "location": "Sea",
        "shadow_size": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 62,
        "name": "Olive Flounder",
        "picture": "https://dodo.ac/np/images/e/ed/Olive_Flounder_NH.png",
        "icon": "https://dodo.ac/np/images/b/b3/Olive_Flounder_NH_Icon.png",
        "sell_nook": 800,
        "location": "Sea",
        "shadow_size": "Very large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 63,
        "name": "Squid",
        "picture": "https://dodo.ac/np/images/3/3b/Squid_NH.png",
        "icon": "https://dodo.ac/np/images/b/bf/Squid_NH_Icon.png",
        "sell_nook": 500,
        "location": "Sea",
        "shadow_size": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 64,
        "name": "Moray Eel",
        "picture": "https://dodo.ac/np/images/7/74/Moray_Eel_NH.png",
        "icon": "https://dodo.ac/np/images/3/3e/Moray_Eel_NH_Icon.png",
        "sell_nook": 2000,
        "location": "Sea",
        "shadow_size": "Long",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 65,
        "name": "Ribbon Eel",
        "picture": "https://dodo.ac/np/images/9/9f/Ribbon_Eel_NH.png",
        "icon": "https://dodo.ac/np/images/2/26/Ribbon_Eel_NH_Icon.png",
        "sell_nook": 600,
        "location": "Sea",
        "shadow_size": "Long",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 66,
        "name": "Tuna",
        "picture": "https://dodo.ac/np/images/6/60/Tuna_NH.png",
        "icon": "https://dodo.ac/np/images/4/4b/Tuna_NH_Icon.png",
        "sell_nook": 7000,
        "location": "Pier",
        "shadow_size": "Huge",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 67,
        "name": "Blue Marlin",
        "picture": "https://dodo.ac/np/images/0/0e/Blue_Marlin_NH.png",
        "icon": "https://dodo.ac/np/images/2/2a/Blue_Marlin_NH_Icon.png",
        "sell_nook": 10000,
        "location": "Pier",
        "shadow_size": "Huge",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 68,
        "name": "Giant Trevally",
        "picture": "https://dodo.ac/np/images/1/1a/Giant_Trevally_NH.png",
        "icon": "https://dodo.ac/np/images/1/17/Giant_Trevally_NH_Icon.png",
        "sell_nook": 4500,
        "location": "Pier",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 69,
        "name": "Mahi-Mahi",
        "picture": "https://dodo.ac/np/images/c/ce/Mahi-Mahi_NH.png",
        "icon": "https://dodo.ac/np/images/d/d6/Mahi-Mahi_NH_Icon.png",
        "sell_nook": 6000,
        "location": "Pier",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 70,
        "name": "Ocean Sunfish",
        "picture": "https://dodo.ac/np/images/c/c6/Ocean_Sunfish_NH.png",
        "icon": "https://dodo.ac/np/images/e/eb/Ocean_Sunfish_NH_Icon.png",
        "sell_nook": 4000,
        "location": "Sea",
        "shadow_size": "Very large (finned)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 AM \u2013 9 PM"
    },
    {
        "index": 71,
        "name": "Ray",
        "picture": "https://dodo.ac/np/images/6/66/Ray_NH.png",
        "icon": "https://dodo.ac/np/images/9/9b/Ray_NH_Icon.png",
        "sell_nook": 3000,
        "location": "Sea",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 AM \u2013 9 PM"
    },
    {
        "index": 72,
        "name": "Saw Shark",
        "picture": "https://dodo.ac/np/images/4/44/Saw_Shark_NH.png",
        "icon": "https://dodo.ac/np/images/4/45/Saw_Shark_NH_Icon.png",
        "sell_nook": 12000,
        "location": "Sea",
        "shadow_size": "Very large (finned)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 73,
        "name": "Hammerhead Shark",
        "picture": "https://dodo.ac/np/images/4/45/Hammerhead_Shark_NH.png",
        "icon": "https://dodo.ac/np/images/e/ec/Hammerhead_Shark_NH_Icon.png",
        "sell_nook": 8000,
        "location": "Sea",
        "shadow_size": "Very large (finned)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 74,
        "name": "Great White Shark",
        "picture": "https://dodo.ac/np/images/4/41/Great_White_Shark_NH.png",
        "icon": "https://dodo.ac/np/images/2/20/Great_White_Shark_NH_Icon.png",
        "sell_nook": 15000,
        "location": "Sea",
        "shadow_size": "Very large (finned)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 75,
        "name": "Whale Shark",
        "picture": "https://dodo.ac/np/images/b/ba/Whale_Shark_NH.png",
        "icon": "https://dodo.ac/np/images/4/4f/Whale_Shark_NH_Icon.png",
        "sell_nook": 13000,
        "location": "Sea",
        "shadow_size": "Very large (finned)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 76,
        "name": "Suckerfish",
        "picture": "https://dodo.ac/np/images/3/3a/Suckerfish_NH.png",
        "icon": "https://dodo.ac/np/images/d/de/Suckerfish_NH_Icon.png",
        "sell_nook": 1500,
        "location": "Sea",
        "shadow_size": "Very large (finned)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day"
    },
    {
        "index": 77,
        "name": "Football Fish",
        "picture": "https://dodo.ac/np/images/e/ef/Football_Fish_NH.png",
        "icon": "https://dodo.ac/np/images/3/34/Football_Fish_NH_Icon.png",
        "sell_nook": 2500,
        "location": "Sea",
        "shadow_size": "Large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 PM \u2013 9 AM"
    },
    {
        "index": 78,
        "name": "Oarfish",
        "picture": "https://dodo.ac/np/images/a/ae/Oarfish_NH.png",
        "icon": "https://dodo.ac/np/images/5/50/Oarfish_NH_Icon.png",
        "sell_nook": 9000,
        "location": "Sea",
        "shadow_size": "Huge",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 0,
        "time": "All day"
    },
    {
        "index": 79,
        "name": "Barreleye",
        "picture": "https://dodo.ac/np/images/4/40/Barreleye_NH.png",
        "icon": "https://dodo.ac/np/images/e/e0/Barreleye_NH_Icon.png",
        "sell_nook": 15000,
        "location": "Sea",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 PM \u2013 4 AM"
    },
    {
        "index": 80,
        "name": "Coelacanth",
        "picture": "https://dodo.ac/np/images/b/b5/Coelacanth_NH.png",
        "icon": "https://dodo.ac/np/images/4/45/Coelacanth_NH_Icon.png",
        "sell_nook": 15000,
        "location": "Sea (raining)",
        "shadow_size": "Huge",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day"
    }
]